### ISSUE TITLE
Replace all occurrence of "right" click?

### ISSUE THREAD

**Issue by ryonakano** [elementary/triage#101]
### What Happened?

We sometimes says "right" click to represent secondary click. However, some users may prefer swapping left & right buttons on the mouse or touchpad because they're left-handed. Assuming secondary click equals "right" click might not be good thinking about this?

But this might be a really nitpicking and the word "right click" is commonly used in other softwares or in our everyday conversation. So feel free to close if you think this is not a valid issue.

### Steps to Reproduce

Search "right click" on our Weblate instance:

https://l10n.elementary.io/search/?offset=1&q=right+click+language%3Aen&sort_by=-priority%2Cposition&checksum=

### Expected Behavior

The all occurrence of "right click" should be replaced some alternative word that considers left-handed people, e.g. "secondary click"

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
N/A
```

### Hardware Info

N/A

**Comment by cassidyjames** [comment]
From looking at your Weblate link, it looks like only one or two places where it is used instead of "secondary click," but is occasionally used as a way to explain what we mean by "secondary click" since many users may be more familiar with "right click." I think it makes sense to open issues/PRs on any specific instance we're using "right click" instead of "secondary click," or places we could be more clear (e.g. rephrasing to "right click on a mouse by default" or similar).

**Comment by ryonakano** [comment]
I see, thank you for your quick response!
