### ISSUE TITLE
screen rotation problem

### ISSUE THREAD

**Issue by dubeyshreyas** [elementary/triage#213]
there are several problems in Hera but what I found extremely problematic are 
1. screen rotation
2. bluetooth drivers
3. wifi drivers are not working properly

I am using 64bit machine with 4 gb ram and intel i3 3rd gen

**Comment by danirabbit** [comment]
Thanks for your report! Unfortunately there's not enough information here to take action as reported. Individual reports should be filed for each issue. Please also use the supplied issue template to provide all the necessary information. See [our contributor guide](https://docs.elementary.io/contributor-guide/feedback/reporting-issues) for more info.

Issues with Drivers are also generally out of scope for elementary OS. We get our drivers from Ubuntu's Linux Kernel, so driver issues should be reported upstream there.

Closing as "Incomplete" since there isn't enough information to take action on "screen rotation" and drivers are out of scope
