### ISSUE TITLE
"Community" bot makes StackExchange very messy

### ISSUE THREAD

**Issue by lukors** [elementary/triage#99]
The [elementary StackExchange](https://elementaryos.stackexchange.com/) is the official place to get community support.

There's a bot there that keeps bumping old issues, filling up the front page with issues that are not relevant for different reasons:

- The author has stopped responding
- The question has been answered
- The question is too old

It seems like the vast majority of questions on the front page fall into one of these categories. This makes it really hard to get to actual questions one might be able to answer. Also, new questions quickly get bumped off the front page and replaced with the less useful ones.

I'm sure the Community bot bumping old questions was great at some point, but now it feels like it would be better without that feature.

**Comment by RMcNeely** [comment]
I decided to check out what you meant. The top post at the time of my writing is a four year old post about Loki (that was answered in 2017) that was randomly bumped. Is there any way to rein in Community bot?

**Comment by danirabbit** [comment]
elementary doesn’t have any control over StackExchange at all. It’s a completely community run site. So closing this report as there’s nothing we can do about it.

I think long term we probably should move to GitHub discussion as our official support platform since we can moderate, it’s where developers already are, it integrates with slack, etc
